title: Deep into World
your_name: Kousuke Takeuchi
author: Kousuke Takeuchi
email: takeuchi@paso-group.com
description: >- # this means to ignore newlines until "baseurl:"
  Paso Group LLC.のCTOによるデータ分析・クラウドシステムについてのブログ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deepinto.world" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
permalink: /:title.html

twitter:
  username: KousukeTakeuchi
  card: summary
# logo
google_site_verification: tk8xSLFQzTDv5F7QBAWKR9Wzev8Zz9r4ubBSYtc9ffQ
lang: ja_JP

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - amp-jekyll
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
