title: Deep into world
your_name: Kousuke Takeuchi
email: takeuchi@paso-group.com
description: >- # this means to ignore newlines until "baseurl:"
  some description
baseurl: "" # the subpath of your site, e.g. /blog
url: "deepinto.world" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
